name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run build
        run: make

  build_macos:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run build
        run: make

  build_windows:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Test Matrix
        run: |
          cl /Fe"nn_MatrixTest.exe" nn_Matrix.c nn_MatrixTest.c
          nn_MatrixTest.exe
        shell: cmd
      - name: Test Network
        run: |
          cl /Fe"nn_NetworkTest.exe" nn_NetworkTest.c nn_Network.c nn_Matrix.c
          nn_NetworkTest.exe
        shell: cmd
